version: '3.8'

services:
  react-app:
    image: chills-app:latest
    ports:
      - "8082:80"
    environment:
      - REACT_APP_API_URL=http://chillis-restaurant-backend:8081
    restart: unless-stopped
