version: '3.8'

services:
  react-app:
    image: chills-app:latest
    ports:
      - "8082:8082"
    environment:
      - REACT_APP_API_URL=http://172.19.0.3:8081
      - REACT_APP_GOOGLE_ANALYTICS_ID=UA-12345678-1
    restart: unless-stopped
